### ISSUE TITLE
Extension is not shown

### ISSUE THREAD

**Issue by WrongBit** [NeVeSpl/CodeRefactoringsForVisualStudio#3]
I installed extension in VS2022(release), then selected assignment, refactoring bulb appeared. But in context menu there was no any mention of "invert assignment" - where is extension?

**Comment by NeVeSpl** [comment]
Could you show your assignment statement? Maybe you have found one that is not recognized correctly ....
![example](https://user-images.githubusercontent.com/11632757/141146673-a167a497-0ea7-43a5-96f2-16b9357096f4.gif)

**Comment by WrongBit** [comment]
Oh, it was quite simple:
```
var s = "qqq";
var d = s;
var v = d;

```
I selected only line 2 and 3, bulb appeared, but no action for "swap". Doh... seems I understand why it doesn't work here, but I had another code, like:

    someObj["key"] = variable.ToString();

Sorry, this case also irrelevant! Right side is not assignable. Sorry, can you delete completely my issue?
