### ISSUE TITLE
Copy/paste class (request)

### ISSUE THREAD

**Issue by LaraSQP** [NeVeSpl/CodeRefactoringsForVisualStudio#4]
First of all, great extension. A must-have. Thanks for developing it and making it available to all.

This is a request for a new feature.

You might remember "Power commands" for vs2017 and vs2019. It included a "Copy/paste class". Also a must-have.

Unfortunately, it seems that there will be no vs2022 version. Thus, my request. You might be able to code this feature.

Thanks again.

**Comment by NeVeSpl** [comment]
Sorry but I do not find this feature very useful.

**Comment by LaraSQP** [comment]
I understand. Thank you for considering it.
