### ISSUE TITLE
Record mapping not working as expected

### ISSUE THREAD

**Issue by anandthirumala** [NeVeSpl/CodeRefactoringsForVisualStudio#5]
Hello NeVeSpl,

Thanks for creating the CodeRefactoringsForVisualStudio, the mapping is a very helpful tool. Very kind of you to create this, it will save us a lot of time, especially for people who don't like AutoMapper.

I just noticed that It's not working for pure records as expected, it's doing a class style mapping. Then we will have to go and do manual editing. Please refer to the example given below,

```
public record ValidationResultDto
(
string Data,
bool IsValid
);

public record ValidationResult
(
string Data,
bool IsValid
);

// Generated Code, this won't even compile without making changes

public ValidationResult GetValidationResult(ValidationResultDto dto)
{
var result= new ValidationResult()
{
Data= dto.Data,
IsValid = dto.IsValid,
};

return result;
}

// Edited Code

public ValidationResult GetValidationResult(ValidationResultDto dto)
{
var result = new ValidationResult
(
dto.Data,
dto.IsValid
);

return result;
}
```
So, could you please us know if this is something you would like to support?

Thanks a lot in advance.

**Comment by NeVeSpl** [comment]
Support for positional records will be added in the upcoming 2.1 version.

**Comment by anandthirumala** [comment]
This is great news. Looking forward. Thanks a lot.

**Comment by anandthirumala** [comment]
Thanks, I will try this today. Very kind of you.
